name: Pull Request Validation

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm install
    - name: ESLint Validation
      run: npm run lint
    - name: Stylelint Validation
      run: npm run lint:style
    - name: Execute Unit Tests
      run: npm run test:unit